/*
 * runtime.c - Minimal C runtime for Spinor AOT compiled programs
 *
 * This runtime provides the main() entry point that calls the
 * spinor_main() function generated by the LLVM AOT compiler.
 *
 * Usage:
 *   clang runtime.c output.ll -o app
 *   ./app
 */

#include <stdio.h>
#include <stdint.h>

/* External function generated by Spinor LLVM AOT compiler */
extern int64_t spinor_main(void);

int main(void) {
    int64_t result = spinor_main();
    printf("%lld\n", (long long)result);
    return 0;
}
