{-# LANGUAGE OverloadedStrings #-}

{-|
Module      : Spinor.Template
Description : Project template definitions for `spinor init`

This module contains the template content for generating new Spinor projects.
Each constant represents a file that will be created when running `spinor init`.
-}
module Spinor.Template
  ( mainSpin
  , testSpin
  , gitignore
  , claudeMd
  , teamsMd
  , sampleTaskMd
  ) where

import Data.Text (Text)
import qualified Data.Text as T

-- | Template for src/main.spin - Entry point with basic examples
mainSpin :: Text
mainSpin = T.unlines
  [ ";; main.spin - Entry point for your Spinor application"
  , ""
  , ";; Define the package for this module"
  , "(defpackage :main"
  , "  (:export main greet))"
  , "(in-package :main)"
  , ""
  , ";; A simple greeting function"
  , "(defun greet (name)"
  , "  (string-append \"Hello, \" name \"!\"))"
  , ""
  , ";; Main entry point"
  , "(defun main ()"
  , "  (print (greet \"World\")))"
  , ""
  , ";; Run main when this file is executed"
  , "(main)"
  ]

-- | Template for test/test.spin - Basic test examples
testSpin :: Text
testSpin = T.unlines
  [ ";; test.spin - Test suite for your Spinor application"
  , ""
  , "(defpackage :test"
  , "  (:use :main))"
  , "(in-package :test)"
  , ""
  , ";; Test the greet function"
  , "(test \"greet returns proper greeting\""
  , "  (assert (string=? (greet \"Alice\") \"Hello, Alice!\")))"
  , ""
  , ";; Test arithmetic operations"
  , "(test \"basic arithmetic works\""
  , "  (assert (= (+ 2 3) 5))"
  , "  (assert (= (* 4 5) 20)))"
  , ""
  , ";; Test list operations"
  , "(test \"list operations work\""
  , "  (assert (= (car (list 1 2 3)) 1))"
  , "  (assert (null? (list))))"
  ]

-- | Template for .gitignore
gitignore :: Text
gitignore = T.unlines
  [ "# Build outputs"
  , "dist/"
  , "*.o"
  , "*.hi"
  , "*.c"
  , ""
  , "# Executables"
  , "*.exe"
  , "*.out"
  , ""
  , "# WASM outputs"
  , "*.wasm"
  , "*.js"
  , "*.html"
  , ""
  , "# Editor files"
  , "*~"
  , ".#*"
  , "\\#*\\#"
  , ""
  , "# OS files"
  , ".DS_Store"
  , "Thumbs.db"
  ]

-- | Template for CLAUDE.md - AI agent context file
--
-- This file is designed to provide AI coding assistants (Claude Code, etc.)
-- with all the information needed to understand and work with Spinor projects.
claudeMd :: Text
claudeMd = T.unlines
  [ "# Spinor Project Context"
  , ""
  , "This is a Spinor project - a statically-typed Lisp with Haskell semantics."
  , ""
  , "## Quick Reference"
  , ""
  , "### Build & Run Commands"
  , ""
  , "```bash"
  , "# Run a Spinor file"
  , "spinor src/main.spin"
  , ""
  , "# Run tests"
  , "spinor test/test.spin"
  , ""
  , "# Compile to native binary (via C + GCC)"
  , "spinor build src/main.spin"
  , ""
  , "# Compile to WebAssembly (via C + Emscripten)"
  , "spinor build src/main.spin --wasm"
  , ""
  , "# Generate C source only"
  , "spinor compile src/main.spin"
  , ""
  , "# Start interactive REPL"
  , "spinor"
  , ""
  , "# Start LSP server (for editor integration)"
  , "spinor lsp"
  , ""
  , "# Start Swank server (for Emacs SLY/SLIME)"
  , "spinor server --port 4005"
  , ""
  , "# Start MCP server (for AI agent integration)"
  , "spinor mcp"
  , "```"
  , ""
  , "## Language Overview"
  , ""
  , "Spinor combines Lisp syntax with Haskell-style semantics:"
  , ""
  , "- **Syntax**: S-expressions (parentheses-based, prefix notation)"
  , "- **Type System**: Hindley-Milner type inference (like Haskell/ML)"
  , "- **Evaluation**: Strict evaluation (call-by-value)"
  , "- **Compilation**: Transpiles to C, then to native binary or WASM"
  , ""
  , "### Core Syntax"
  , ""
  , "```lisp"
  , ";; Variable definition"
  , "(def x 42)"
  , "(def name \"Alice\")"
  , ""
  , ";; Function definition"
  , "(defun add (a b)"
  , "  (+ a b))"
  , ""
  , ";; Anonymous function (lambda)"
  , "(fn (x) (* x x))"
  , ""
  , ";; Let bindings (local variables)"
  , "(let ((x 10)"
  , "      (y 20))"
  , "  (+ x y))"
  , ""
  , ";; Conditionals"
  , "(if (> x 0)"
  , "    \"positive\""
  , "    \"non-positive\")"
  , ""
  , ";; Pattern matching"
  , "(match value"
  , "  ((Just x) (+ x 1))"
  , "  (Nothing  0))"
  , "```"
  , ""
  , "### Type System"
  , ""
  , "Types are inferred automatically. No type annotations needed in most cases:"
  , ""
  , "```lisp"
  , ";; Inferred: Int -> Int -> Int"
  , "(defun add (a b) (+ a b))"
  , ""
  , ";; Inferred: Int -> Bool"
  , "(defun is-positive (n) (> n 0))"
  , ""
  , ";; Polymorphic function: a -> a"
  , "(defun identity (x) x)"
  , "```"
  , ""
  , "### Algebraic Data Types (ADT)"
  , ""
  , "```lisp"
  , ";; Define a Maybe type"
  , "(data Maybe"
  , "  (Just a)"
  , "  (Nothing))"
  , ""
  , ";; Define a List type"
  , "(data MyList"
  , "  (Cons a (MyList a))"
  , "  (Nil))"
  , ""
  , ";; Use with pattern matching"
  , "(defun safe-head (lst)"
  , "  (match lst"
  , "    ((Cons x _) (Just x))"
  , "    (Nil        Nothing)))"
  , "```"
  , ""
  , "### Package System"
  , ""
  , "Spinor has a Common Lisp-style package system:"
  , ""
  , "```lisp"
  , ";; Define a package with exports"
  , "(defpackage :mylib"
  , "  (:export public-fn helper))"
  , ""
  , ";; Switch to the package"
  , "(in-package :mylib)"
  , ""
  , ";; Define functions in the package"
  , "(defun public-fn (x) ...)"
  , "(defun helper (x) ...)"
  , "(defun private-fn (x) ...)  ; Not exported"
  , ""
  , ";; In another file, use the package"
  , "(defpackage :app"
  , "  (:use :mylib))  ; Import all exported symbols"
  , "(in-package :app)"
  , ""
  , "(public-fn 42)  ; Works"
  , "(helper 10)     ; Works"
  , "; (private-fn 1) ; Error: not exported"
  , "```"
  , ""
  , "## Experimental Features"
  , ""
  , "### Linear Types & Ownership (Experimental)"
  , ""
  , "Rust-inspired ownership system for automatic memory management:"
  , ""
  , "```lisp"
  , ";; Declare a linear variable (must be used exactly once)"
  , "(linear resource (open-file \"data.txt\"))"
  , "(process resource)  ; Consumes resource"
  , ""
  , ";; Explicit drop"
  , "(linear handle (create-handle))"
  , "(drop handle)  ; Explicitly release"
  , "```"
  , ""
  , "### Region-based Memory (Experimental)"
  , ""
  , "Arena allocator for efficient bulk memory management:"
  , ""
  , "```lisp"
  , ";; Create a region and allocate within it"
  , "(with-region r"
  , "  (let ((x (alloc-in r 42))"
  , "        (s (alloc-in r \"hello\")))"
  , "    (process x s)))"
  , ";; All memory in region r is freed here"
  , "```"
  , ""
  , "## Project Structure"
  , ""
  , "```"
  , "project-name/"
  , "  src/"
  , "    main.spin      # Entry point"
  , "  test/"
  , "    test.spin      # Test suite"
  , "  CLAUDE.md        # This file (AI context)"
  , "  .gitignore       # Git ignore rules"
  , "```"
  , ""
  , "## Common Patterns"
  , ""
  , "### Testing"
  , ""
  , "```lisp"
  , "(test \"description\""
  , "  (assert condition)"
  , "  (assert (= expected actual)))"
  , "```"
  , ""
  , "### Error Handling"
  , ""
  , "```lisp"
  , ";; Using Maybe for optional values"
  , "(defun safe-div (a b)"
  , "  (if (= b 0)"
  , "      Nothing"
  , "      (Just (/ a b))))"
  , ""
  , ";; Pattern match on result"
  , "(match (safe-div 10 2)"
  , "  ((Just result) (print result))"
  , "  (Nothing       (print \"Division by zero\")))"
  , "```"
  , ""
  , "### List Processing"
  , ""
  , "```lisp"
  , ";; Built-in list functions"
  , "(car lst)           ; First element"
  , "(cdr lst)           ; Rest of list"
  , "(cons x lst)        ; Prepend element"
  , "(null? lst)         ; Check if empty"
  , "(list 1 2 3)        ; Create list"
  , ""
  , ";; Higher-order functions"
  , "(map f lst)         ; Apply f to each element"
  , "(filter pred lst)   ; Keep elements where pred is true"
  , "(fold f init lst)   ; Reduce list with f"
  , "```"
  , ""
  , "## Style Guidelines"
  , ""
  , "1. Use `defpackage` and `in-package` for modular code"
  , "2. Top-level definitions use `def` (values) or `defun` (functions)"
  , "3. Type errors are reported before execution - fix type mismatches first"
  , "4. Prefer pattern matching over nested conditionals"
  , "5. Use descriptive function names with hyphens (kebab-case)"
  , ""
  , "## MCP Server (AI Agent Integration)"
  , ""
  , "Spinor provides an MCP (Model Context Protocol) server for AI agent integration."
  , "This allows AI agents like Claude Code to interact with your Spinor project."
  , ""
  , "### Available Tools"
  , ""
  , "- **eval**: Evaluate Spinor code in the current context"
  , "- **typecheck**: Infer the type of a Spinor expression"
  , "- **macroexpand**: Expand macros and return the resulting S-expression"
  , "- **list-symbols**: List available symbols in a package"
  , ""
  , "### Setup for Claude Code"
  , ""
  , "Add this to your Claude Code MCP settings:"
  , ""
  , "```json"
  , "{"
  , "  \"mcpServers\": {"
  , "    \"spinor\": {"
  , "      \"command\": \"spinor\","
  , "      \"args\": [\"mcp\"]"
  , "    }"
  , "  }"
  , "}"
  , "```"
  , ""
  , "## AI Development Workflow (IMPORTANT)"
  , ""
  , "**When modifying or creating Spinor code, you MUST follow this workflow:**"
  , ""
  , "1. Write or modify the `.spin` file"
  , "2. Run `spinor check --json <file>` to verify syntax and type correctness"
  , "3. If errors are returned, parse the JSON output and fix issues at the specified line/column"
  , "4. Repeat steps 2-3 until no errors remain"
  , ""
  , "### Example verification command:"
  , ""
  , "```bash"
  , "spinor check --json src/main.spin"
  , "```"
  , ""
  , "### Success output:"
  , ""
  , "```json"
  , "{\"status\":\"success\",\"command\":\"check\",\"message\":\"Type check passed. 5 expressions analyzed.\"}"
  , "```"
  , ""
  , "### Error output:"
  , ""
  , "```json"
  , "{\"status\":\"error\",\"errors\":[{\"file\":\"src/main.spin\",\"line\":12,\"col\":5,\"message\":\"Type mismatch\",\"code\":\"TYPE_ERROR\"}]}"
  , "```"
  , ""
  , "**Do not skip this verification step.** Always ensure code is type-correct before proceeding."
  , ""
  , "## Troubleshooting"
  , ""
  , "- **Type error**: Check that argument types match function signatures"
  , "- **Undefined variable**: Ensure the variable is defined or imported"
  , "- **Package not found**: Check that the package is defined with `defpackage`"
  , "- **Build failed**: Verify GCC/Emscripten is installed and in PATH"
  , ""
  , "## Agent Teams Mode"
  , ""
  , "If operating as part of an Agent Teams workflow (multiple AI agents working in parallel),"
  , "you MUST follow the rules and protocols defined in `.agents/TEAMS.md`."
  , ""
  , "Key points:"
  , "- Check `.agents/tasks/todo/` for available tasks"
  , "- Move task to `.agents/tasks/in-progress/` when starting work"
  , "- Use `spinor check --json` for self-verification"
  , "- Move completed tasks to `.agents/tasks/review/`"
  ]

-- | Template for .agents/TEAMS.md - Agent behavior rules and protocols
teamsMd :: Text
teamsMd = T.unlines
  [ "# Agent Teams Protocol"
  , ""
  , "This document defines the rules and protocols for AI agents working on this project."
  , ""
  , "## Roles"
  , ""
  , "### Team Lead"
  , ""
  , "- **Responsibility**: Break down project goals into individual task files"
  , "- **Task Creation**: Create task files in `.agents/tasks/todo/`"
  , "- **Review**: Check tasks in `.agents/tasks/review/`"
  , "  - Run `spinor check --json <file>` to verify type correctness"
  , "  - If passed, move to `.agents/tasks/done/`"
  , "  - If failed, add comments and move back to `todo/` or `in-progress/`"
  , ""
  , "### Teammate (Developer)"
  , ""
  , "- **Pick Task**: Select a task from `.agents/tasks/todo/`"
  , "- **Claim Task**: Add your name to the task file and move it to `in-progress/`"
  , "- **Implement**: Write Spinor code following the task requirements"
  , "- **Self-Verify**: Run `spinor check --json <file>` to ensure type correctness"
  , "- **Submit**: Move the task file to `.agents/tasks/review/`"
  , ""
  , "## Task Lifecycle"
  , ""
  , "```"
  , "todo/ -> in-progress/ -> review/ -> done/"
  , "  ^                        |"
  , "  +-- (rejected) ----------+"
  , "```"
  , ""
  , "## Task File Format"
  , ""
  , "Each task file (`.md`) should contain:"
  , ""
  , "```markdown"
  , "# Task: <title>"
  , ""
  , "## Description"
  , "<what needs to be done>"
  , ""
  , "## Acceptance Criteria"
  , "- [ ] Criteria 1"
  , "- [ ] Criteria 2"
  , ""
  , "## Assigned To"
  , "<agent name or empty>"
  , ""
  , "## Status"
  , "<todo | in-progress | review | done>"
  , ""
  , "## Notes"
  , "<implementation notes, review comments>"
  , "```"
  , ""
  , "## Lock Protocol"
  , ""
  , "- Use file move (`mv`) as an atomic lock operation"
  , "- Only one agent can work on a task at a time"
  , "- If a file is in `in-progress/`, it is claimed by another agent"
  , ""
  , "## Communication"
  , ""
  , "- Use `.agents/mailboxes/<agent-name>/` for direct messages"
  , "- Create a `.md` file with the message content"
  , "- Check your mailbox periodically for new messages"
  , ""
  , "## Verification Commands"
  , ""
  , "```bash"
  , "# Check syntax and types (JSON output for parsing)"
  , "spinor check --json <file>"
  , ""
  , "# Run tests"
  , "spinor test/<file>.spin"
  , "```"
  , ""
  , "## Best Practices"
  , ""
  , "1. Always verify your code with `spinor check --json` before submitting"
  , "2. Keep tasks small and focused"
  , "3. Document your changes in the task file"
  , "4. Communicate blockers via mailbox"
  ]

-- | Template for sample task in .agents/tasks/todo/
sampleTaskMd :: Text
sampleTaskMd = T.unlines
  [ "# Task: Implement a map function"
  , ""
  , "## Description"
  , ""
  , "Implement a `map` function in `twister/list.spin` that applies a function"
  , "to each element of a list and returns a new list with the results."
  , ""
  , "## Acceptance Criteria"
  , ""
  , "- [ ] `map` function is defined in `twister/list.spin`"
  , "- [ ] Works with empty lists: `(map f ())` returns `()`"
  , "- [ ] Works with non-empty lists: `(map (fn (x) (+ x 1)) (list 1 2 3))` returns `(2 3 4)`"
  , "- [ ] Type checks pass: `spinor check --json twister/list.spin`"
  , ""
  , "## Assigned To"
  , ""
  , "(unassigned)"
  , ""
  , "## Status"
  , ""
  , "todo"
  , ""
  , "## Notes"
  , ""
  , "This is a sample task demonstrating the Agent Teams workflow."
  , "Feel free to modify or replace with your actual project tasks."
  ]
