{-# LANGUAGE OverloadedStrings #-}

{-|
Module      : Spinor.Template
Description : Project template definitions for `spinor init`

This module contains the template content for generating new Spinor projects.
Each constant represents a file that will be created when running `spinor init`.
-}
module Spinor.Template
  ( mainSpin
  , testSpin
  , gitignore
  , claudeMd
  ) where

import Data.Text (Text)
import qualified Data.Text as T

-- | Template for src/main.spin - Entry point with basic examples
mainSpin :: Text
mainSpin = T.unlines
  [ ";; main.spin - Entry point for your Spinor application"
  , ""
  , ";; Define the package for this module"
  , "(defpackage :main"
  , "  (:export main greet))"
  , "(in-package :main)"
  , ""
  , ";; A simple greeting function"
  , "(defun greet (name)"
  , "  (string-append \"Hello, \" name \"!\"))"
  , ""
  , ";; Main entry point"
  , "(defun main ()"
  , "  (print (greet \"World\")))"
  , ""
  , ";; Run main when this file is executed"
  , "(main)"
  ]

-- | Template for test/test.spin - Basic test examples
testSpin :: Text
testSpin = T.unlines
  [ ";; test.spin - Test suite for your Spinor application"
  , ""
  , "(defpackage :test"
  , "  (:use :main))"
  , "(in-package :test)"
  , ""
  , ";; Test the greet function"
  , "(test \"greet returns proper greeting\""
  , "  (assert (string=? (greet \"Alice\") \"Hello, Alice!\")))"
  , ""
  , ";; Test arithmetic operations"
  , "(test \"basic arithmetic works\""
  , "  (assert (= (+ 2 3) 5))"
  , "  (assert (= (* 4 5) 20)))"
  , ""
  , ";; Test list operations"
  , "(test \"list operations work\""
  , "  (assert (= (car (list 1 2 3)) 1))"
  , "  (assert (null? (list))))"
  ]

-- | Template for .gitignore
gitignore :: Text
gitignore = T.unlines
  [ "# Build outputs"
  , "dist/"
  , "*.o"
  , "*.hi"
  , "*.c"
  , ""
  , "# Executables"
  , "*.exe"
  , "*.out"
  , ""
  , "# WASM outputs"
  , "*.wasm"
  , "*.js"
  , "*.html"
  , ""
  , "# Editor files"
  , "*~"
  , ".#*"
  , "\\#*\\#"
  , ""
  , "# OS files"
  , ".DS_Store"
  , "Thumbs.db"
  ]

-- | Template for CLAUDE.md - AI agent context file
--
-- This file is designed to provide AI coding assistants (Claude Code, etc.)
-- with all the information needed to understand and work with Spinor projects.
claudeMd :: Text
claudeMd = T.unlines
  [ "# Spinor Project Context"
  , ""
  , "This is a Spinor project - a statically-typed Lisp with Haskell semantics."
  , ""
  , "## Quick Reference"
  , ""
  , "### Build & Run Commands"
  , ""
  , "```bash"
  , "# Run a Spinor file"
  , "spinor src/main.spin"
  , ""
  , "# Run tests"
  , "spinor test/test.spin"
  , ""
  , "# Compile to native binary (via C + GCC)"
  , "spinor build src/main.spin"
  , ""
  , "# Compile to WebAssembly (via C + Emscripten)"
  , "spinor build src/main.spin --wasm"
  , ""
  , "# Generate C source only"
  , "spinor compile src/main.spin"
  , ""
  , "# Start interactive REPL"
  , "spinor"
  , ""
  , "# Start LSP server (for editor integration)"
  , "spinor lsp"
  , ""
  , "# Start Swank server (for Emacs SLY/SLIME)"
  , "spinor server --port 4005"
  , ""
  , "# Start MCP server (for AI agent integration)"
  , "spinor mcp"
  , "```"
  , ""
  , "## Language Overview"
  , ""
  , "Spinor combines Lisp syntax with Haskell-style semantics:"
  , ""
  , "- **Syntax**: S-expressions (parentheses-based, prefix notation)"
  , "- **Type System**: Hindley-Milner type inference (like Haskell/ML)"
  , "- **Evaluation**: Strict evaluation (call-by-value)"
  , "- **Compilation**: Transpiles to C, then to native binary or WASM"
  , ""
  , "### Core Syntax"
  , ""
  , "```lisp"
  , ";; Variable definition"
  , "(def x 42)"
  , "(def name \"Alice\")"
  , ""
  , ";; Function definition"
  , "(defun add (a b)"
  , "  (+ a b))"
  , ""
  , ";; Anonymous function (lambda)"
  , "(fn (x) (* x x))"
  , ""
  , ";; Let bindings (local variables)"
  , "(let ((x 10)"
  , "      (y 20))"
  , "  (+ x y))"
  , ""
  , ";; Conditionals"
  , "(if (> x 0)"
  , "    \"positive\""
  , "    \"non-positive\")"
  , ""
  , ";; Pattern matching"
  , "(match value"
  , "  ((Just x) (+ x 1))"
  , "  (Nothing  0))"
  , "```"
  , ""
  , "### Type System"
  , ""
  , "Types are inferred automatically. No type annotations needed in most cases:"
  , ""
  , "```lisp"
  , ";; Inferred: Int -> Int -> Int"
  , "(defun add (a b) (+ a b))"
  , ""
  , ";; Inferred: Int -> Bool"
  , "(defun is-positive (n) (> n 0))"
  , ""
  , ";; Polymorphic function: a -> a"
  , "(defun identity (x) x)"
  , "```"
  , ""
  , "### Algebraic Data Types (ADT)"
  , ""
  , "```lisp"
  , ";; Define a Maybe type"
  , "(data Maybe"
  , "  (Just a)"
  , "  (Nothing))"
  , ""
  , ";; Define a List type"
  , "(data MyList"
  , "  (Cons a (MyList a))"
  , "  (Nil))"
  , ""
  , ";; Use with pattern matching"
  , "(defun safe-head (lst)"
  , "  (match lst"
  , "    ((Cons x _) (Just x))"
  , "    (Nil        Nothing)))"
  , "```"
  , ""
  , "### Package System"
  , ""
  , "Spinor has a Common Lisp-style package system:"
  , ""
  , "```lisp"
  , ";; Define a package with exports"
  , "(defpackage :mylib"
  , "  (:export public-fn helper))"
  , ""
  , ";; Switch to the package"
  , "(in-package :mylib)"
  , ""
  , ";; Define functions in the package"
  , "(defun public-fn (x) ...)"
  , "(defun helper (x) ...)"
  , "(defun private-fn (x) ...)  ; Not exported"
  , ""
  , ";; In another file, use the package"
  , "(defpackage :app"
  , "  (:use :mylib))  ; Import all exported symbols"
  , "(in-package :app)"
  , ""
  , "(public-fn 42)  ; Works"
  , "(helper 10)     ; Works"
  , "; (private-fn 1) ; Error: not exported"
  , "```"
  , ""
  , "## Experimental Features"
  , ""
  , "### Linear Types & Ownership (Experimental)"
  , ""
  , "Rust-inspired ownership system for automatic memory management:"
  , ""
  , "```lisp"
  , ";; Declare a linear variable (must be used exactly once)"
  , "(linear resource (open-file \"data.txt\"))"
  , "(process resource)  ; Consumes resource"
  , ""
  , ";; Explicit drop"
  , "(linear handle (create-handle))"
  , "(drop handle)  ; Explicitly release"
  , "```"
  , ""
  , "### Region-based Memory (Experimental)"
  , ""
  , "Arena allocator for efficient bulk memory management:"
  , ""
  , "```lisp"
  , ";; Create a region and allocate within it"
  , "(with-region r"
  , "  (let ((x (alloc-in r 42))"
  , "        (s (alloc-in r \"hello\")))"
  , "    (process x s)))"
  , ";; All memory in region r is freed here"
  , "```"
  , ""
  , "## Project Structure"
  , ""
  , "```"
  , "project-name/"
  , "  src/"
  , "    main.spin      # Entry point"
  , "  test/"
  , "    test.spin      # Test suite"
  , "  CLAUDE.md        # This file (AI context)"
  , "  .gitignore       # Git ignore rules"
  , "```"
  , ""
  , "## Common Patterns"
  , ""
  , "### Testing"
  , ""
  , "```lisp"
  , "(test \"description\""
  , "  (assert condition)"
  , "  (assert (= expected actual)))"
  , "```"
  , ""
  , "### Error Handling"
  , ""
  , "```lisp"
  , ";; Using Maybe for optional values"
  , "(defun safe-div (a b)"
  , "  (if (= b 0)"
  , "      Nothing"
  , "      (Just (/ a b))))"
  , ""
  , ";; Pattern match on result"
  , "(match (safe-div 10 2)"
  , "  ((Just result) (print result))"
  , "  (Nothing       (print \"Division by zero\")))"
  , "```"
  , ""
  , "### List Processing"
  , ""
  , "```lisp"
  , ";; Built-in list functions"
  , "(car lst)           ; First element"
  , "(cdr lst)           ; Rest of list"
  , "(cons x lst)        ; Prepend element"
  , "(null? lst)         ; Check if empty"
  , "(list 1 2 3)        ; Create list"
  , ""
  , ";; Higher-order functions"
  , "(map f lst)         ; Apply f to each element"
  , "(filter pred lst)   ; Keep elements where pred is true"
  , "(fold f init lst)   ; Reduce list with f"
  , "```"
  , ""
  , "## Style Guidelines"
  , ""
  , "1. Use `defpackage` and `in-package` for modular code"
  , "2. Top-level definitions use `def` (values) or `defun` (functions)"
  , "3. Type errors are reported before execution - fix type mismatches first"
  , "4. Prefer pattern matching over nested conditionals"
  , "5. Use descriptive function names with hyphens (kebab-case)"
  , ""
  , "## MCP Server (AI Agent Integration)"
  , ""
  , "Spinor provides an MCP (Model Context Protocol) server for AI agent integration."
  , "This allows AI agents like Claude Code to interact with your Spinor project."
  , ""
  , "### Available Tools"
  , ""
  , "- **eval**: Evaluate Spinor code in the current context"
  , "- **typecheck**: Infer the type of a Spinor expression"
  , "- **macroexpand**: Expand macros and return the resulting S-expression"
  , "- **list-symbols**: List available symbols in a package"
  , ""
  , "### Setup for Claude Code"
  , ""
  , "Add this to your Claude Code MCP settings:"
  , ""
  , "```json"
  , "{"
  , "  \"mcpServers\": {"
  , "    \"spinor\": {"
  , "      \"command\": \"spinor\","
  , "      \"args\": [\"mcp\"]"
  , "    }"
  , "  }"
  , "}"
  , "```"
  , ""
  , "## Troubleshooting"
  , ""
  , "- **Type error**: Check that argument types match function signatures"
  , "- **Undefined variable**: Ensure the variable is defined or imported"
  , "- **Package not found**: Check that the package is defined with `defpackage`"
  , "- **Build failed**: Verify GCC/Emscripten is installed and in PATH"
  ]
