{-# LANGUAGE OverloadedStrings #-}

{-|
Module      : Spinor.Compiler.LLVM
Description : LLVM IR Code Generator for Spinor AOT Compilation

This module generates LLVM IR text from Spinor AST for AOT (Ahead-of-Time)
compilation. The generated IR can be compiled with clang along with runtime.c
to produce standalone native executables.

No C++ LLVM bindings are required — all IR is generated as pure Haskell text.

= Usage

@
cabal run spinor -- build-llvm fib.spin
./fib
@

= Supported Expressions

- Integer literals: @42@
- Boolean literals: @#t@, @#f@ (represented as i64: 1/0)
- Arithmetic: @(+ a b)@, @(- a b)@, @(* a b)@
- Comparison: @(= a b)@, @(< a b)@
- Conditionals: @(if cond then else)@
- Function definitions: @(def name (fn (args...) body))@
- Function calls: @(name args...)@
-}
module Spinor.Compiler.LLVM
  ( compileToLLVM
  , LLVMCompileError(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Data.List (partition)
import Control.Monad.State.Strict
import Spinor.Syntax (Expr(..))

-- | LLVM compilation errors
data LLVMCompileError
  = LLVMUnsupportedExpr Text
  | LLVMCompileError Text
  deriving (Show, Eq)

-- | Code generation state
data CodeGenState = CodeGenState
  { cgsTempCounter :: !Int           -- ^ Counter for temporary variables
  , cgsLabelCounter :: !Int          -- ^ Counter for labels
  , cgsCode :: ![Text]               -- ^ Generated code lines (reversed)
  , cgsFunctions :: ![Text]          -- ^ Generated function definitions
  , cgsDefinedFuncs :: ![Text]       -- ^ List of defined function names
  } deriving (Show)

type CodeGen a = State CodeGenState a

-- | Initial code generation state
initialState :: CodeGenState
initialState = CodeGenState 0 0 [] [] []

-- | Get a fresh temporary variable name
freshTemp :: CodeGen Text
freshTemp = do
  s <- get
  let n = cgsTempCounter s
  put s { cgsTempCounter = n + 1 }
  pure $ "%t" <> T.pack (show n)

-- | Get a fresh label name
freshLabel :: Text -> CodeGen Text
freshLabel prefix = do
  s <- get
  let n = cgsLabelCounter s
  put s { cgsLabelCounter = n + 1 }
  pure $ prefix <> T.pack (show n)

-- | Emit a line of code
emit :: Text -> CodeGen ()
emit line = modify $ \s -> s { cgsCode = line : cgsCode s }

-- | Emit a function definition
emitFunction :: Text -> CodeGen ()
emitFunction fn = modify $ \s -> s { cgsFunctions = fn : cgsFunctions s }

-- | Register a defined function name
registerFunc :: Text -> CodeGen ()
registerFunc name = modify $ \s -> s { cgsDefinedFuncs = name : cgsDefinedFuncs s }

-- | Compile a list of Spinor expressions to LLVM IR text
compileToLLVM :: [Expr] -> Either LLVMCompileError Text
compileToLLVM exprs =
  let (defExprs, mainExprs) = partition isDefExpr exprs
      result = evalState (compileProgramM defExprs mainExprs) initialState
  in result

-- | Check if expression is a function definition
isDefExpr :: Expr -> Bool
isDefExpr (EList _ (ESym _ "def" : _)) = True
isDefExpr _ = False

-- | Compile the entire program
compileProgramM :: [Expr] -> [Expr] -> CodeGen (Either LLVMCompileError Text)
compileProgramM defExprs mainExprs = do
  -- First, register all function names
  mapM_ registerDefName defExprs

  -- Compile function definitions
  defResults <- mapM compileDefExpr defExprs
  case sequence defResults of
    Left err -> pure $ Left err
    Right _ -> do
      -- Compile main expressions
      mainResult <- compileMainFunction mainExprs
      case mainResult of
        Left err -> pure $ Left err
        Right _ -> do
          s <- get
          let funcs = T.unlines (reverse $ cgsFunctions s)
          pure $ Right $ T.unlines
            [ "; Spinor AOT Compiled Module"
            , "; Generated by Spinor LLVM Compiler"
            , ""
            , funcs
            ]

-- | Register function name from def expression
registerDefName :: Expr -> CodeGen ()
registerDefName (EList _ [ESym _ "def", ESym _ name, _]) = registerFunc name
registerDefName _ = pure ()

-- | Compile a function definition
compileDefExpr :: Expr -> CodeGen (Either LLVMCompileError ())
compileDefExpr (EList _ [ESym _ "def", ESym _ name, EList _ (ESym _ "fn" : EList _ params : body)]) = do
  -- Reset state for new function
  modify $ \s -> s { cgsTempCounter = 0, cgsLabelCounter = 0, cgsCode = [] }

  let paramNames = [n | ESym _ n <- params]
      llvmParams = T.intercalate ", " ["i64 %" <> p | p <- paramNames]
      mangledName = mangleName name

  -- Compile function body
  case body of
    [bodyExpr] -> do
      result <- compileExpr bodyExpr
      case result of
        Left err -> pure $ Left err
        Right resultVar -> do
          emit $ "  ret i64 " <> resultVar
          s <- get
          let bodyCode = T.unlines (reverse $ cgsCode s)
          emitFunction $ T.unlines
            [ "define i64 @" <> mangledName <> "(" <> llvmParams <> ") {"
            , "entry:"
            , bodyCode
            , "}"
            ]
          pure $ Right ()
    _ -> pure $ Left $ LLVMCompileError $ "Invalid function body: " <> name

compileDefExpr other = pure $ Left $ LLVMUnsupportedExpr $ "Invalid def: " <> T.pack (show other)

-- | Compile the main function (spinor_main)
compileMainFunction :: [Expr] -> CodeGen (Either LLVMCompileError ())
compileMainFunction [] = do
  emitFunction $ T.unlines
    [ "define i64 @spinor_main() {"
    , "entry:"
    , "  ret i64 0"
    , "}"
    ]
  pure $ Right ()

compileMainFunction exprs = do
  -- Reset state for main function
  modify $ \s -> s { cgsTempCounter = 0, cgsLabelCounter = 0, cgsCode = [] }

  -- Compile each expression, keeping the last result
  results <- mapM compileExpr exprs
  case sequence results of
    Left err -> pure $ Left err
    Right vars -> do
      let lastVar = if null vars then "0" else last vars
      emit $ "  ret i64 " <> lastVar
      s <- get
      let bodyCode = T.unlines (reverse $ cgsCode s)
      emitFunction $ T.unlines
        [ "define i64 @spinor_main() {"
        , "entry:"
        , bodyCode
        , "}"
        ]
      pure $ Right ()

-- | Compile an expression, returning the LLVM value (variable or constant)
compileExpr :: Expr -> CodeGen (Either LLVMCompileError Text)

-- Integer literal
compileExpr (EInt _ n) = pure $ Right $ T.pack (show n)

-- Boolean literal
compileExpr (EBool _ b) = pure $ Right $ if b then "1" else "0"

-- Symbol reference (variable)
compileExpr (ESym _ name) = pure $ Right $ "%" <> name

-- Arithmetic: (+ a b)
compileExpr (EList _ [ESym _ "+", a, b]) = compileBinOp "add" a b

-- Arithmetic: (- a b)
compileExpr (EList _ [ESym _ "-", a, b]) = compileBinOp "sub" a b

-- Arithmetic: (* a b)
compileExpr (EList _ [ESym _ "*", a, b]) = compileBinOp "mul" a b

-- Comparison: (= a b)
compileExpr (EList _ [ESym _ "=", a, b]) = do
  resultA <- compileExpr a
  case resultA of
    Left err -> pure $ Left err
    Right va -> do
      resultB <- compileExpr b
      case resultB of
        Left err -> pure $ Left err
        Right vb -> do
          cmpTemp <- freshTemp
          resultTemp <- freshTemp
          emit $ "  " <> cmpTemp <> " = icmp eq i64 " <> va <> ", " <> vb
          emit $ "  " <> resultTemp <> " = zext i1 " <> cmpTemp <> " to i64"
          pure $ Right resultTemp

-- Comparison: (< a b)
compileExpr (EList _ [ESym _ "<", a, b]) = do
  resultA <- compileExpr a
  case resultA of
    Left err -> pure $ Left err
    Right va -> do
      resultB <- compileExpr b
      case resultB of
        Left err -> pure $ Left err
        Right vb -> do
          cmpTemp <- freshTemp
          resultTemp <- freshTemp
          emit $ "  " <> cmpTemp <> " = icmp slt i64 " <> va <> ", " <> vb
          emit $ "  " <> resultTemp <> " = zext i1 " <> cmpTemp <> " to i64"
          pure $ Right resultTemp

-- If expression: (if cond then else)
compileExpr (EList _ [ESym _ "if", condExpr, thenExpr, elseExpr]) = do
  -- Compile condition
  condResult <- compileExpr condExpr
  case condResult of
    Left err -> pure $ Left err
    Right condVar -> do
      -- Compare condition with 0
      condBool <- freshTemp
      emit $ "  " <> condBool <> " = icmp ne i64 " <> condVar <> ", 0"

      -- Generate labels
      thenLabel <- freshLabel "then"
      elseLabel <- freshLabel "else"
      mergeLabel <- freshLabel "merge"

      -- Conditional branch
      emit $ "  br i1 " <> condBool <> ", label %" <> thenLabel <> ", label %" <> elseLabel

      -- Then block
      emit $ thenLabel <> ":"
      thenResult <- compileExpr thenExpr
      case thenResult of
        Left err -> pure $ Left err
        Right thenVar -> do
          emit $ "  br label %" <> mergeLabel
          thenEndLabel <- getCurrentLabel thenLabel

          -- Else block
          emit $ elseLabel <> ":"
          elseResult <- compileExpr elseExpr
          case elseResult of
            Left err -> pure $ Left err
            Right elseVar -> do
              emit $ "  br label %" <> mergeLabel
              elseEndLabel <- getCurrentLabel elseLabel

              -- Merge block with phi
              emit $ mergeLabel <> ":"
              resultVar <- freshTemp
              emit $ "  " <> resultVar <> " = phi i64 [" <> thenVar <> ", %" <> thenEndLabel <> "], [" <> elseVar <> ", %" <> elseEndLabel <> "]"
              pure $ Right resultVar

-- Function call
compileExpr (EList _ (ESym _ name : args)) = do
  s <- get
  if name `elem` cgsDefinedFuncs s
    then do
      -- User-defined function call
      argResults <- mapM compileExpr args
      case sequence argResults of
        Left err -> pure $ Left err
        Right argVars -> do
          resultVar <- freshTemp
          let argList = T.intercalate ", " ["i64 " <> v | v <- argVars]
          emit $ "  " <> resultVar <> " = call i64 @" <> mangleName name <> "(" <> argList <> ")"
          pure $ Right resultVar
    else pure $ Left $ LLVMUnsupportedExpr $ "Unknown function: " <> name

-- Unsupported expression
compileExpr other = pure $ Left $ LLVMUnsupportedExpr $ T.pack (show other)

-- | Compile a binary operation
compileBinOp :: Text -> Expr -> Expr -> CodeGen (Either LLVMCompileError Text)
compileBinOp op a b = do
  resultA <- compileExpr a
  case resultA of
    Left err -> pure $ Left err
    Right va -> do
      resultB <- compileExpr b
      case resultB of
        Left err -> pure $ Left err
        Right vb -> do
          resultVar <- freshTemp
          emit $ "  " <> resultVar <> " = " <> op <> " i64 " <> va <> ", " <> vb
          pure $ Right resultVar

-- | Get current label (for phi node - simplified version)
getCurrentLabel :: Text -> CodeGen Text
getCurrentLabel baseLabel = pure baseLabel

-- | Mangle a function name to be valid in LLVM IR
mangleName :: Text -> Text
mangleName name = "spinor_" <> T.concatMap sanitize name
  where
    sanitize c
      | c == '-' = "_"
      | c == '?' = "_p"
      | c == '!' = "_x"
      | otherwise = T.singleton c
